name: Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  qualify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check code for syntax issues
        run: npm run lint
      - name: Check code for formatting issues
        run: npm run prettier
      - name: Analyze internal dependencies
        run: npm run depcruise
      - name: Run unit tests
        run: npm test
      - name: Compile TypeScript
        run: npm run compile
