name: Platform checks

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: Operating System
        options:
          - macos-latest
          - ubuntu-latest
          - windows-latest
      node-version:
        type: choice
        description: Node.js version
        options:
          - 12.x
          - 14.x
          - 16.x

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ github.event.inputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ github.event.inputs.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check code for syntax issues
        run: npm run lint
      - name: Check code for formatting issues
        run: npm run prettier
      - name: Run unit tests
        run: npm test
      - name: Compile TypeScript
        run: npm run compile
