name: Visual overview

on:
  workflow_dispatch:

jobs:
  visualize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install dependencies
        run: npm ci
      - name: Visualize internal dependencies
        run: |
          npm run depcruise -- -T dot -f depcruise.dot
          dot depcruise.dot -T svg -o depcruise.svg
      - name: Archive dependency graph as artifact
        uses: actions/upload-artifact@v2
        with:
          name: internal-dependencies
          path: |
            depcruise.svg
            depcruise.dot
